name: package metadata
description: Get package metadata from the GitHub Packages container registry.
branding:
  color: red
  icon: file-minus
inputs:
  github-token:
    description: A GitHub token with the 'read:packages' permission.
    required: true
  package-name:
    description: Name of the package to fetch the metadata.
    required: false
  namespace:
    default: false
    description: Set to true if you are running this action against a personal account package.
    required: false
  
  repository:
    default: ${{ github.repository }}
    description: The owner and repository name. 
    required: false
runs:
  using: node16
  main: index.js